INSERT INTO Extras (Name)
VALUES
    ("Bluetooth"),
    ("DAB Radio"),
    ("Warming in the seats"),
    ("Autonomous driving"),
    ("Long range"),
    ("Four wheel drive"),
    ("Glass roof"),
    ("Yellow"),
    ("Retro"),
    ("Three stripes"),
    ("Original tire discs"),
    ("Tow hook"),
    ("Travel box on the roof"),
    ("Warming in the steering wheel"),
    ("Warming in the mirrors"),
    ("Warming in the tires"),
    ("Warming under the rubber rugs"),
    ("Warming 360"),
    ("FM radio"),
    ("CD player"),
    ("Metallic paint"),
    ("Five doors"),
    ("Very economic");