CREATE TABLE Location (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(50) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    IsBusiness BOOLEAN NOT NULL
);

CREATE TABLE Car (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Maker VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Year INTEGER NOT NULL,
    Fuel VARCHAR(10) NOT NULL,
    Transmission VARCHAR(20) NOT NULL,
    Seats INTEGER NOT NULL,
    Extras VARCHAR(255) NOT NULL,
    Images VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE Storage (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LID INTEGER NOT NULL,
    CID INTEGER NOT NULL,
    Price INTEGER NOT NULL,
    FOREIGN KEY (LID) REFERENCES Location(ID),
    FOREIGN KEY (CID) REFERENCES Car(ID)
);

CREATE TABLE User (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Terms BOOLEAN NOT NULL,
    IsAdming BOOLEAN NOT NULL
);

CREATE TABLE PurchaseHistory (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UID INTEGER NOT NULL,
    SID INTEGER NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    FOREIGN KEY (UID) REFERENCES User(ID),
    FOREIGN KEY (SID) REFERENCES Storage(ID)
);